all: 
	echo "please input : \"python3 mots_2D.py {file}\" and {file} as a file : list of words."

test:
	python3 mots_2D.py __motsFR.txt

final: 
	python3 mots_2D_2.py
 
clean:
	rm -f count2D_EN.bin output_FR12.txt

